return {
  { import = 'plugins.configs.colorscheme' },
  { import = 'plugins.configs.treesitter' },
  { import = 'plugins.configs.telescope' },
  { import = 'plugins.configs.lualine' },
  { import = 'plugins.configs.which-key' },
  { import = 'plugins.configs.gitsigns' },
  { import = 'plugins.configs.neo-tree' },
  { import = 'plugins.configs.oil' },
  { import = 'plugins.configs.trouble' },
  { import = 'plugins.configs.conform' },
  { import = 'plugins.configs.autopairs' },
  { import = 'plugins.configs.indent-blankline' },
  { import = 'plugins.configs.vim-maximizer' },
  { import = 'plugins.configs.mini' },
  { import = 'plugins.configs.dropbar' },
  { import = 'plugins.configs.supermaven' },
  { import = 'plugins.configs.todo-comments' },
  { import = 'plugins.configs.debug' },
  { import = 'plugins.configs.harpoon' },
  { import = 'plugins.configs.peek' },

  -- LSP-related plugins
  { import = 'plugins.configs.lsp' },
  { import = 'plugins.configs.lsp.completion' },
}
